# Site settings
title: Fong Phone
email: chriswininger@fongphone.com
description: Welcome to the fong phone, an open source phone app that will drone your head to space
baseurl: ""
url: "http://phongphone.com"

github: https://github.com/chriswininger/FongPhone
disqus_shortname: "chriswininger"
google_analytics: 38179684

paginate: 10
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown: kramdown
permalink : /:title/

gems: [jekyll-paginate]
